language: node_js
node_js:
  - "0.12"
before_install: npm install -g grunt-cli
install: cd reveal-js && npm install
script: grunt package
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&

  eval key=\$encrypted_6e5668afcb42_key &&
  eval iv=\$encrypted_6e5668afcb42_iv &&

  mkdir -p ~/.ssh &&
  openssl aes-256-cbc -K $key -iv $iv -in ../id_rsa.enc -out ~/.ssh/id_rsa -d &&
  chmod 600 ~/.ssh/id_rsa &&

  git clone --branch gh-pages git@github.com:globin/es6-presentation-built deploy_docs &&

  cd deploy_docs &&
  git config user.name "doc upload bot" &&
  git config user.email "nobody@example.com" &&
  rm -rf * &&
  unzip ../es6.zip &&
  echo es6.glob.in > CNAME &&
  git add -A . &&
  git commit -qm "doc upload for es6-presentation ($TRAVIS_REPO_SLUG)" &&
  git push -q origin gh-pages
